name: Developer Test

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  Test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: jokes_test
          POSTGRES_PASSWORD: jokes_test
          POSTGRES_DB: jokes_test
        ports:
          - 5432:5432
    env:
      OS: ubuntu-latest
      PYTHON: '3.11'
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: "3.11"
      - name: 'Run Tests'
        env:
          CONNECTION_STRING: postgresql://jokes_test:jokes_test@localhost:5432/jokes_test
          TEST_CONNECTION_STRING: postgresql://jokes_test:jokes_test@localhost:5432/jokes_test
          TEST: True
        run: |
          python -m pip install --upgrade pip          
          pip install -r requirements/dev.txt
          python -m pytest --cov app
